#!/usr/bin/env node
/**
 * M365 Mail MCP Server — entrypoint.
 *
 * Generated by juvantlabs/juvant-tools scaffold mcp-server on
 * 2026-07-02. Conforms to handbook docs/repo-types/mcp-server.md.
 *
 * IMPORTANT: All non-protocol output must go to stderr (`console.error`).
 * Writing to stdout corrupts the MCP stdio JSON-RPC framing. CI lint
 * rules enforce this in `juvantlabs/*-mcp-server` repos.
 */

import { realpathSync } from "node:fs";
import { pathToFileURL } from "node:url";

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const LOG_LEVEL = process.env.MCP_SERVER_LOG_LEVEL ?? "info";

const server = new Server(
  {
    name: "@juvantlabs/m365-mail-mcp-server",
    version: "0.0.1",
  },
  {
    capabilities: {
      tools: {},
    },
  },
);

// =====================================================================
// Tool list — register each tool here.
// =====================================================================
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      // {
      //   name: "<vendor>:<tool-name>",
      //   description: "<one-line description>",
      //   inputSchema: { type: "object", properties: { ... }, required: [...] },
      // },
    ],
  };
});

// =====================================================================
// Tool dispatch — handle calls per tool name.
// =====================================================================
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name } = request.params;

  switch (name) {
    // case "<vendor>:<tool-name>": {
    //   const args = request.params.arguments;
    //   return await handleToolName(args);
    // }

    default:
      throw new Error(`Unknown tool: ${name}`);
  }
});

// =====================================================================
// Boot — connect to stdio and run.
// =====================================================================
async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  // No stdout writes here. Server listens on stdio until the client closes.
  console.error(`[m365-mail-mcp-server] running on stdio (log level: ${LOG_LEVEL})`);
}

/**
 * Detect whether this module is the entry point (vs imported by tests
 * or other code). When invoked via the npm `bin` symlink (npm puts
 * the package's bin into `node_modules/.bin/<name>` as a symlink to
 * `dist/index.js`), `process.argv[1]` is the symlink path, not the
 * underlying file. Resolve symlinks via `realpathSync` so the
 * comparison against `import.meta.url` matches in all three cases:
 *
 *   - Bin invocation:  `npx @juvantlabs/m365-mail-mcp-server`
 *   - Direct:          `node dist/index.js`
 *   - Dev (tsx):       `tsx src/index.ts`
 *
 * Also resolves macOS's `/tmp` → `/private/tmp` symlink, which would
 * otherwise produce a false-negative under direct invocation in /tmp.
 */
function isInvokedAsMain(): boolean {
  if (!process.argv[1]) return false;
  try {
    const realPath = realpathSync(process.argv[1]);
    return import.meta.url === pathToFileURL(realPath).href;
  } catch {
    return false;
  }
}

if (isInvokedAsMain()) {
  main().catch((err) => {
    console.error("[m365-mail-mcp-server] fatal:", err);
    process.exit(1);
  });
}
